### PR TITLE
Support screenshots on Wayland via XDG Desktop Portals

### PR DESCRIPTION
**Pull request by MrCarroll**
This commit should provide support for Wayland sessions to take screenshots using the New Screenshot action.

Future improvements:

- Improve reliability of detecting if the system is running in a Wayland session (considering e.g, nested composition)
- Properly parent the screenshot dialog to the Pinta main window.

I'm not sure how the translations work; whether the translations should be part of this commit or future commits. Also if there's a better location to put the DBus classes, please feel free to recommend a better path.

(And sorry in advance if there's any obvious formatting errors, I've tried to keep in line with Pinta's conventions, but the spaces between function and parameters is unnatural to me!)

### CODE REVIEW

**Comment by cameronwhite** [comment]
Looks good!
- I wouldn't worry too much about detecting Wayland. If the portal works well I'd imagine we should just use it by default on Linux in the future - it sounds like the current method will probably not work anymore in GTK4 anyways (https://docs.gtk.org/gtk4/migrating-3to4.html#stop-using-gdk_pixbuf_get_from_window-and-gdk_cairo_set_source_window). So maybe the generated code could go into a `DBus` subfolder rather than `Wayland` to keep things general?
- The formatting looks pretty good other than one `return` statement that's indented oddly in the diff - you could just run it through `dotnet format` to fix things up
- The translations look good - the only optional step would be to run `make updatepot` to update the translation template ([details](https://github.com/PintaProject/Pinta/wiki/Translations)), but I can also do that afterwards since I need to upload the translation template to Launchpad anyways

**Comment by MrCarroll** [comment]
Unfortunately I couldn't get the `make updatepot` to work on my machine, I'll leave that to you if you're happy to take over it on your end.

The concern I'd have with removing the check for the `$WAYLAND_DISPLAY` variable is that it effectively then degrades the experience slightly for X11 users because the portals modal dialog won't parent correctly. If there's a function you know about in GtkSharp that could get the X11 ID of the root window, that'd solve the issue. (Similarly with Wayland ID's, but I've already checked for that one and it doesn't exist as far as I can tell).

The other concern I'd have with removing the `$WAYLAND_DISPLAY` check is that it'll also expose X11 users on BSD systems, where the XDG portals don't exist (yet? there's possible interest in porting them in the future, but no commitments if I remember correctly). In the context of GTK4 I suppose there's no choice, but in GTK3, this is still a regression. Maybe it's worth making the OS check specifically Linux, rather than the X11 enum? Alternatively, maybe it's worth removing the `return` statement in the catch block, so that the default behaviour is tried if the DBus calls fail rather than get cancelled.

P.S feel free to squash these commits when/if you merge them, the formatting fixes for example don't add much to the history

**Comment by cameronwhite** [comment]
No problem! I can do the translation stuff after merging

That's a good point about BSD. I'm leaning towards the last suggestion, so falling back to the old behaviour if the dbus stuff fails (except for the Wayland case, where the portal error message should be displayed since we know the old behaviour won't work)
I don't see anything in GtkSharp for getting at the X11 window id, but I'm okay with that minor regression - using the system's screenshot UI and preparing for Gtk4 is a big improvement IMO

**Comment by cameronwhite** [comment]
No problem! I can do the translation stuff after merging

That's a good point about BSD. I'm leaning towards the last suggestion, so falling back to the old behaviour if the dbus stuff fails (except for the Wayland case, where the portal error message should be displayed since we know the old behaviour won't work)
I don't see anything in GtkSharp for getting at the X11 window id, but I'm okay with that minor regression - using the system's screenshot UI and preparing for Gtk4 is a big improvement IMO

**Comment by MrCarroll** [comment]
I think this PR is in a mergable position now, given the acknowledged regressions and the issues getting the translations makefile working.

The last 2 commits brought up the question of whether the error message about the portals being unavailable should be shown on X11, but personally I think the choice is obvious, if they're on X11 and don't have the portals, it's probably not worth nagging about them because the legacy logic works fine for now. Meanwhile on Wayland the portals are the only option available, so the error is justified. In GTK4 that'll probably need re-evaluating.

**Comment by cameronwhite** [comment]
Looks good, thanks!

**Pull request merged**
