### PR TITLE
Fix unexpected interactions of text tool

### LINKED ISSUE #1097: Palatte color changes interacts with text tool in unexpected ways
**Description**
When writing a text, but not finalizing it before selecting another tool and then changing primary color does not change the color of the text until the new tool is used, then the text is finalized with the new color. 

**To Reproduce**
Write text without finalizing, select other tool, change primary color, use new tool.

**Additional Info**
I've been seeing strange behaviour regarding text finalizing overall. Sometimes the text does not finalize properly leaving a piece of text that cannot be interacted with until a new text is written forcing the old one to finalize, but have not been able to reproduce this consistently. Most of this behaviour seems to happen when switching tool without finalizing the text first. Perhaps the best solution is to finalize text on tool switches?

**Version**
Windows 10, Master branch Pinta (version 2.1.2?)

### PR DESCRIPTION
**Pull request by TheodorLasse**
Fixes #1097

Moved the color objects used for drawing text to the CurrentTextEngine and then only updating those colors when the color palette changes while the text tool is selected. 

Removed FinalizeText on surface cloning. This seems to be the code that caused finalizations of text when using another tool. The text seems to finalize properly now, but I am not completely sure why the code was there to begin with, so this might have subtly broke something.

### CODE REVIEW

**Comment by cameronwhite** [comment]
Thanks for looking at this!
I'm not sure that removing that finalization code is correct - in the video below, you can see that if the text isn't finalized when you start drawing with the brush tool, then the text is overlaid on top of the brush stroke as if it were another layer


https://github.com/user-attachments/assets/cef9de7f-20a2-46ac-a35a-18142689761d

**Comment by TheodorLasse** [comment]
It seems I misunderstood. I have since then been looking into the text tool behaving strangely on startup but I did not find what was causing the inconsistent behaviour. I reverted the change to not finalize text when using another tool, so currently this pull request only fixes the problem of the text suddenly switching colors when switching to another tool and changing color before using that tool.

**Comment by cameronwhite** [comment]
Actually I think that code block you were removing might hint at the startup issue - that LayerCloned event handler is only added if there is an open document when the text tool is activated, but on startup perhaps the text tool is activated before the default empty document?
That event handler might need to be shifted somewhere else so that it's added more reliably, e.g. whenever the text tool has created some unfinalized text?

**Comment by cameronwhite** [comment]
I've committed a fix for the finalization issue in 8deeaf93ed158af99725793b824a23d5b2fb50fa, so I'll merge these changes for the colours now. Thanks for working on this!!

**Pull request merged**
