### PR TITLE
Bump version in appdata.xml to 1.8

### PR DESCRIPTION
**Pull request by darkdragon-001**
Don't forget to add release date once released!

Is it possible to automatically generate [version](https://github.com/PintaProject/Pinta/blob/gtk3-v2/configure.ac#L2)  and [release date](https://github.com/PintaProject/Pinta/blob/gtk3-v2/CHANGELOG.md)? I don't want to add a PR for every release since it seems to be forgotten all the time...

### CODE REVIEW

**Comment by cameronwhite** [comment]
I do have it in the release checklist (https://github.com/PintaProject/Pinta/wiki/Release-Checklist) to update that file, so hopefully it would have been caught ...
The version number in configure.ac is part of the standard steps for bumping to a new version

**Comment by darkdragon-001** [comment]
@cameronwhite Is it possible to substitute the version number into appdata.xml automatically in the build process?

**Comment by cameronwhite** [comment]
Possibly, I'm not sure what the right autotools incantations are :) 
Maybe something in xdg/Makefile.am , or by using $VERSION in the source file?

**Comment by darkdragon-001** [comment]
I never really used autotools. Would be awesome if someone could figure out...

@cameronwhite I noticed that [flathub requires a valid timestamp (so `xx` can't be used for the release date)](https://flathub.org/builds/#/builders/10/builds/4612/steps/10/logs/stdio). Can you please merge again from my appdata branch?

**Comment by cameronwhite** [comment]
Sure, I've just manually pushed a fix.

**Pull request merged**
