### PR TITLE
Normalized line endings to `LF`

### PR DESCRIPTION
**Pull request by Lehonti**
Since I often modify the code on a Windows machine, some `CR` `LF` line endings are inserted by the IDE when I format the code automatically, which I then have to remove by doing a search and replace, otherwise the build will fail on GitHub (due to format checking).

Today, after doing the routine search and replace after making a change, two extra files were listed by Git. Of course I had to undo the changes on those files since they are unrelated to what I was changing. But removing it every time could get tedious, so let's fix the issue while it's only a couple of files.

### CODE REVIEW

**Comment by MrCarroll** [comment]
You can configure git to automatically convert line endings for you, but if there's a strong preference for Pinta to use LF exclusively, it could be forced via .gitattributes. (https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings)

**Comment by Lehonti** [comment]
Thanks for the configuration tip @MrCarroll. In this case the `CR` `LF` line endings are not my own, but they are on the code that I downloaded from GitHub. The line endings have always been exclusively `LF` until these two files were created, so I'm assuming that that's what's preferred.

I may implement your tip on a future pull request. For now I think this is the best thing to do.

**Comment by cameronwhite** [comment]
Yeah I think these were unintentional - I'd be okay with always forcing LF endings to avoid needing whitespace-related fixes like this

**Comment by Lehonti** [comment]
If you do, you could get rid of [Pinta](https://github.com/PintaProject/Pinta/tree/master)/[tests](https://github.com/PintaProject/Pinta/tree/master/tests)/[Pinta.Core.Tests](https://github.com/PintaProject/Pinta/tree/master/tests/Pinta.Core.Tests)/[Assets](https://github.com/PintaProject/Pinta/tree/master/tests/Pinta.Core.Tests/Assets)
/sixcolorsoutput_crlf.ppm and get the `*.ppm` export to be always written with `LF` line endings. I haven't taken the time to look at how it's done so I added versions with both line ending conventions, but it needn't be that way.

**Pull request merged**
