### PR TITLE
Update docking

### PR DESCRIPTION
**Pull request by jpobst**
This is the first step of pulling in the latest docking library from MonoDevelop.  This is simply the updated bits for the parts we use today, it does not include any new features yet.

It also moves all the code to a separate library to help keep it isolated.

I tested it on Windows and Mac, it has not been tested on Linux.

### CODE REVIEW

**Comment by cameronwhite** [comment]
I'll give it a test on Linux before merging, but I think there will probably need to be an update to the Makefile to include Pinta.Docking in the list of dlls

**Comment by cameronwhite** [comment]
I did some brief testing and it seems to work okay on Linux. The only issue I noticed was that the auto-hide and close buttons don't highlight when the mouse hovers over them. I haven't tested the docking changes on Windows so I don't know if that's platform-specific or not.

**Comment by jpobst** [comment]
Doesn't highlight on Windows either, so it must be a change to the library.  They are definitely new icons.

**Comment by jpobst** [comment]
Never mind, I found a method I had just stubbed out that fixes this.

**Comment by cameronwhite** [comment]
OK, thanks. Could you look at fixing the errors on the Travis CI build? I think the [SetSource extension method] (https://github.com/PintaProject/Pinta/blob/master/Pinta.Core/Extensions/CairoExtensions.cs#L569) that I added to CairoExtensions.cs might be need there as well.

**Comment by jpobst** [comment]
Looks like that was it, thanks for the tip!

**Pull request merged**
