### PR TITLE
Significantly beef up the "New Image" dialog.

### PR DESCRIPTION
**Pull request by jpobst**
Adds the following features to the New Image dialog:
- Preset sizes
- Portrait/Landscape orientation
- Initial background color
- Image preview

new-dialog

### CODE REVIEW

**Comment by cameronwhite** [comment]
Looks really good! Just a couple issues i noticed while testing:

- If the previously-used width and height are 8000x8000, then when I open the New Image dialog and use the preset menu to switch to 800x600, it actually changes to 600x800 instead. I think the issue might be that it got switched over to portrait from landscape?
- The layout was a bit cramped on Windows (see image below).
untitled

**Comment by jpobst** [comment]
- It respects whether you have it set to Portrait or Landscape when you do the preset, and adjusts the preset values to fit your orientation.  Maybe I am over-thinking it here and should just do what the preset says.  :)
- You must have larger than normal fonts set. Looks like if I don't ask for an explicit size I can get it to size itself properly.  Will fix.

**Comment by cameronwhite** [comment]
Thanks, the sizing looks good now!

IMO, I think it makes more sense to do what the preset says, instead of trying to maintain the user's orientation setting.

**Comment by jpobst** [comment]
I took a different option that preserves the user's Orientation choice without being confusing.  If you change it from Landscape to Portrait all the Preset values will update to be portrait instead of landscape, so the label and the result match.  (800 x 600 -> 600 x 800, etc.)

**Pull request merged**
