### PR TITLE
In `FrostedGlassEffect.Render`, extracted calculation of target pixel color into its own method

### PR DESCRIPTION
**Pull request by Lehonti**

### CODE REVIEW

**Comment by cameronwhite** [comment]
This seems much slower now, just testing on a 2000px image takes many seconds now when it was only a second or so before.
I haven't tried running the benchmarks yet, but can you do some more performance testing of this change please?

**Comment by Lehonti** [comment]
That is indeed very strange. I suppose that reading the properties `Width` and `Height` from `ImageSurface` several times for every pixel doesn't really help, so I will tackle it from that angle when I get to it

**Comment by Lehonti** [comment]
I haven't run the tests, but from a subjective perspective there doesn't seem to be much difference :/

For now, I have cached the properties I mentioned in a settings object.

Still, I could run and compare benchmarks if the problem persists.

**Comment by Lehonti** [comment]
Here's the benchmarks for `FrostedGlassEffect` currently in `master`

```
Mean = 2.147 s, StdErr = 0.006 s (0.26%), N = 15, StdDev = 0.022 s
Min = 2.112 s, Q1 = 2.134 s, Median = 2.144 s, Q3 = 2.160 s, Max = 2.182 s
IQR = 0.025 s, LowerFence = 2.097 s, UpperFence = 2.197 s
ConfidenceInterval = [2.124 s; 2.170 s] (CI 99.9%), Margin = 0.023 s (1.08% of Mean)
Skewness = 0.03, Kurtosis = 1.91, MValue = 2
```

And here's the benchmarks after caching the properties (that is, from the newest commit, and not the one that was causing you trouble). I had to unseal the class but didn't push that because I see that you already did it

```
Mean = 937.978 ms, StdErr = 4.571 ms (0.49%), N = 16, StdDev = 18.285 ms
Min = 909.473 ms, Q1 = 922.117 ms, Median = 944.858 ms, Q3 = 949.779 ms, Max = 964.695 ms
IQR = 27.663 ms, LowerFence = 880.623 ms, UpperFence = 991.273 ms
ConfidenceInterval = [919.360 ms; 956.596 ms] (CI 99.9%), Margin = 18.618 ms (1.98% of Mean)
Skewness = -0.26, Kurtosis = 1.6, MValue = 2
```

**Comment by cameronwhite** [comment]
Thanks! It seems much better now testing the latest version

**Pull request merged**
