### PR TITLE
Fix problem with selection tool handles still being enabled while invisible after deselecting

### PR DESCRIPTION
**Pull request by codecat**
This one bothered me, so I decided to make a (quick) fix for it. The second commit is kind of an ugly workaround, but it works, and is the fastest way to get the job done properly.

### CODE REVIEW

**Comment by tsukiRep** [comment]
@cameronwhite please merge tha nk you

**Comment by EmilyRosina** [comment]
Pleeeeeeeease just merge it (after rebasing obvs) but this is such a vital thing to not have in an image editor :anger:

**Comment by Restioson** [comment]
Any reason that this hasn't been merged yet? Seems overdue.

**Comment by cameronwhite** [comment]
Apologies for losing track of this.
This change is a hacky workaround, so I would prefer a change that fixes the underlying issue (i.e. why isn't the existing `AfterSelectionChange()` handler in the select tool being triggered when the selection is cleared?)

**Comment by jaburns** [comment]
It's a hacky workaround, but it is very small. Would you consider just applying the hack fix and then opening a separate issue to fix the hack in a more correct manner? This way the problem can be solved in the mean time while any developers that feel like solving it correctly come up with a solution.

The app is virtually unusable for me without being able to resize selections, and it's the only issue I have with Pinta.

**Comment by codecat** [comment]
5 years later, and there's activity on this pull request, wow! For what it's worth, I'm not sure how valid this pull request still is, considering stuff seems to have changed quite a bit (judging by the fact that there is now a merge conflict).

I don't use Pinta anymore myself so perhaps a new pull request would be good?

**Comment by jaburns** [comment]
Manually applying the changes in this PR was reasonable. All of the code neighboring the diffs still seems to exist in the same form, but applying these changes now doesn't fix the issue anymore. I guess I'm going to have to dig a little deeper.

**Comment by jaburns** [comment]
Sorry I thought this PR was for something else. I arrived here from this bug report ( https://bugs.launchpad.net/pinta/+bug/1473430 ) which is about not being able to resize the current selection using the move-selected tool, and I see now that this PR is about fixing lingering handles in the selection tool.

Anyway I've implemented "Hold control to resize when you're in the move-selected tool" on a fork, if anyone else lands here from that bug report and is looking for a way to resize the current selection.

I'll make a separate PR for that in case the Pinta developers are interested in merging that feature.

**Comment by topotech** [comment]
> I'll make a separate PR for that in case the Pinta developers are interested in merging that feature.
In which fork?

**Comment by topotech** [comment]
> Anyway I've implemented "Hold control to resize when you're in the move-selected tool" on a fork, if anyone else lands here from that bug report and is looking for a way to resize the current selection.
>

In which fork? :open_mouth:

**Comment by jaburns** [comment]
I implemented it in this PR which has now been merged in to master https://github.com/PintaProject/Pinta/pull/138 . So if you build the latest on master you should have that feature :)

**Comment by cameronwhite** [comment]
This should be fixed by f78d88a5 so I think this PR can be closed now!

**Comment by spitemim** [comment]
I'm really sorry. Right after I left the comment, the resizing started working again. My bad.

**Comment by keef1212** [comment]
Still not here.

**Pull request closed without merging**
