### PR TITLE
Added capability to export to portable pixmap

### PR DESCRIPTION
**Pull request by Lehonti**

### CODE REVIEW

**Comment by cameronwhite** [comment]
Looks good to me, thanks!
How about also adding a unit test for this? :) Since it's a text-based format, comparing some small image against the expected result probably would probably work

**Comment by Lehonti** [comment]
Sure, here's an attempt, but I don't know if it works, because my Ubuntu enviroment can't find GLib, and I haven't had the time to find out why.

**Comment by cameronwhite** [comment]
I haven't looked in depth, but you may need to call the `Module.Initialize()` functions somewhere in Pinta.Core.Tests at startup, similar to https://github.com/PintaProject/Pinta/blob/master/tests/Pinta.Effects.Tests/Utilities.cs#L11 in the effects tests. Right now I only see the text engine test doing this for Pango

**Comment by Lehonti** [comment]
Apparently, that's exactly what was needed. The tests are now running and passing as expected

**Comment by cameronwhite** [comment]
Looks good, thanks!

**Pull request merged**
