### PR TITLE
Removed `WarpEffect` class

### PR DESCRIPTION
**Pull request by Lehonti**
The hierarchy is now flat, and the handling of warp behavior is interface-based and extension method-based.

Some abstractions are leaky, but they reflect what was already there. There is room for improvement and hopefully we can actually improve it at some point, although I wouldn't call this a big priority because this kind of effect is not part of the public API.

### CODE REVIEW

**Comment by cameronwhite** [comment]
I think this is a good start, but I'd probably prefer to go further and remove the`IWarpEffect` inheritance entirely? e.g. if there are just some static utility methods that are called by the effects, that would be easier to manage

**Comment by Lehonti** [comment]
I thought the same, @cameronwhite; it would be great to make calculations accessible without the need for specific interfaces, however, the coupling to services makes this a bit hard; but perhaps you have something specific in mind.

**Comment by cameronwhite** [comment]
> however, the coupling to services makes this a bit hard

The services are just used to set up the render settings, right? I think those could just be passed as parameters into some method which builds it?

**Comment by Lehonti** [comment]
@cameronwhite  please see if these last changes bring the code closer to what you have in mind.

**Comment by Lehonti** [comment]
@cameronwhite please see if these last changes bring the code closer to what you have in mind.

**Comment by cameronwhite** [comment]
That looks good to me - thank you!

**Comment by cameronwhite** [comment]
Related question - is it possible now to enable unit tests for these effects? Previously they were disabled because of references to `PintaCore`

**Comment by Lehonti** [comment]
@cameronwhite not quite yet. These effects depend on `LivePreviewManager` because they have to know the size of the canvas. This is one of the reasons I am trying to refactor the render process so that only a single ROI is passed, and the tiling is habdled internally by the effect. A temporary solution for what you are suggesting could involve extracting an independent, lightweight service that provides the size of the canvas. That would be easier to mock.

**Comment by cameronwhite** [comment]
I think just mocking the live preview manager might be the best for now if that's not too hard to do, since that would add test coverage without any major changes (hopefully)

**Pull request merged**
