### PR TITLE
Pilot for migrating to `Gtk.FileDialog`

### PR DESCRIPTION
**Pull request by Lehonti**
I don't know what to make of this.

As mentioned [here](https://github.com/PintaProject/Pinta/pull/1133#issuecomment-2480642607), it would be good to migrate from `FileChooserNative` (which is deprecated) to `FileDialog`.

However, when the user cancels, an exception (`GLib.GException`) is thrown, but even worse, it doesn't seem to expose what one needs to filter it out cleanly.

On one hand,[ the documentation](https://docs.gtk.org/gtk4/method.FileDialog.open_multiple_finish.html) says that an error is set if the user doesn't choose anything. On the other hand, the `Result` of the `Task<>` is nullable for some reason, and also, having an exception thrown in the first place for a very plausible and common scenario (like a user canceling their choice) is awkward. It makes me wonder if I, the programmer, am doing something wrong.

Should we take this as it is (and perhaps handle all the messy parts in extension methods) or should this be brought up with the gir.core community?

Name | Value | Type
-- | -- | --
Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary   {System.Collections.ListDictionaryInternal}
HResult | -2146233088 | int
HasBeenThrown | true | bool
HelpLink | null | string
InnerException | null | System.Exception
Message | "Dismissed by user" | string
SerializationStackTraceString | " at   Pinta.Actions.OpenDocumentAction.Activated(Object sender, EventArgs e) in   C:\\path\\to\\code\\Pinta_fork\\Pinta\\Actions\\File\\OpenDocumentAction.cs:line   81" | string
SerializationWatsonBuckets | null | object
Source | "Pinta" | string
StackTrace | " at   Pinta.Actions.OpenDocumentAction.<Activated>d__8.MoveNext() in   C:\\path\\to\\code\\Pinta_fork\\Pinta\\Actions\\File\\OpenDocumentAction.cs:line   81" | string
TargetSite | {Void MoveNext()} | System.Reflection.MethodBase   {System.Reflection.RuntimeMethodInfo}
_HResult | -2146233088 | int
_data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary   {System.Collections.ListDictionaryInternal}
_dynamicMethods | null | object[]
_errorHandle | {GLib.Internal.ErrorOwnedHandle} | GLib.Internal.ErrorHandle   {GLib.Internal.ErrorOwnedHandle}
_exceptionMethod | null | System.Reflection.MethodBase
_helpURL | null | string
_innerException | null | System.Exception
_ipForWatsonBuckets | 0x00007ffaac6e6258 | System.UIntPtr
_message | "Dismissed by user" | string
_remoteStackTraceString | null | string
_source | null | string
_stackTrace | {sbyte[192]} | byte[] {sbyte[]}
_stackTraceString | null | string
_watsonBuckets | null | byte[]
_xcode | -532462766 | int
_xptrs | 0x0000000000000000 | System.IntPtr

### CODE REVIEW

**Comment by cameronwhite** [comment]
Yeah, this is probably something to discuss more on the gir.core side.

My two cents:

I think the return value being nullable is reasonable (especially if the binding is automatically generated), since the type info in the .gir file declares the value as nullable - it's only the documentation which explains that null should only occur if an error happens. In this case it is actually a [manually written wrapper](https://github.com/gircore/gir.core/blob/main/src/Libs/Gtk-4.0/Public/FileDialog.cs), but I'm not sure it should be changed since the binding might become automatically generated in the future with further gir.core improvements for async functions

The fact that an error is being returned on cancellation is part of the GTK behaviour, and gir.core just translates those errors into exceptions which is the reasonable thing to do in the majority of cases. I think wrapping it in our own extension methods is fine unless there's a desire upstream to have some similar extension method which handles cancellation more conveniently.

I think it would be good if the exception returned more information like having access to the `Glib.Error` - if we could access the error code then that would feel less hacky than checking the message text. Right now the error isn't exposed at all (https://github.com/gircore/gir.core/blob/main/src/Libs/GLib-2.0/Public/GException.cs)

**Comment by Lehonti** [comment]
Thank you for the explanation, @cameronwhite.

I agree that if these mechanisms correspond to the GTK API we should just take these binding as they are, at least for migration.

I also agree that having an error code would be cleaner.

I just wrapped all the awkward parts in an extension method.

**Comment by cameronwhite** [comment]
Thanks! Wrapping this in an extension method looks good

**Comment by badcel** [comment]
@cameronwhite @Lehonti I took a look at the Exception topic again. Errors can be matched soon.

In regard to the exception throwing itself there is one alternative to the current design: In C there is an `out Error` for a throwable exception. I interpret this parameter in GirCore and throw the exception if the error is set.

I could just make the error parameter available to the public GirCore API surface and not throw myself.

This would have the following characteristics:
- Ignoring / forgetting the parameter means ignoring all errors and thus exceptions from it. This would make a nullable return more plausible.
- if it is handled a user can handle it manually via the error API without creating stack traces.
- A user can decide to create an exception from the error via a method like: `error.ThrowIfSet()` or APIs like `string MyErrorMethod().WithThrow()` or `sting MyErrorMethod().WithError(out Error)`

Doing it this way gives a lot of flexibility and mirrors the C API more closely and allows to convert an error to its C# pendant (exceptions) manually. Actually I like this idea as it fits the "new" GirCore direction of being closer to C and avoids awkward situations like the ones described here.

Doing this would break the API pretty significantly and might not be well received.

So I'm very interested in your thoughts.

**Comment by cameronwhite** [comment]
Yeah that's an interesting idea for cases like this dialog where throwing an exception feels weird. I agree about the concern with it being less idiomatic C#, and possibly annoying if this affects a lot of methods? (not sure offhand how many methods have a GError parameter)
Looking through the Pinta codebase there are only 6 cases where we actually catch a GException specifically - anything else unexpected would fall back to the main exception handler

**Comment by badcel** [comment]
Perhaps I'm going to try this and make a custom Pinta build.

Then we can see how it feels under real world conditions.

**Pull request merged**
