### PR TITLE
Used concurrent collection instead of tile index in `AsyncEffectRenderer`

### PR DESCRIPTION
**Pull request by Lehonti**

### CODE REVIEW

**Comment by cameronwhite** [comment]
I'm not entirely sure whether this is the right direction - for using Parallel.For in the future I think sticking with indices might be easier?

**Comment by Lehonti** [comment]
Thanks for the feedback @cameronwhite 

No problem, we could indeed do it with indices; in fact, we would have to do so in some cases if we want the parallelization of the rendering to be handled inside the `Render()` method; but this might be a good time to discuss the longer-term vision that informed this refactoring approach. This will show that this `ConcurrentQueue` represents the projected default behavior rather than being prescriptive.

I think we can agree that the end goal is allowing effect developers to parallelize the rendering of the effect in question inside the `Render()` method, while having sane defaults that allow the user to think about the specifics as little as they want.

As for my idea of how to implement this ideal, I was thinking of refactoring the entire functionality of `AsyncEffectRenderer` into a handle that provides more information and more control of the render process.

I think that, in its simplest form, 

The following example (which is not final, but just for clarification) could explain what I mean:

```csharp
interface IRenderHandle
{
    void Cancel ();
    double GetProgress ();
}

// This will allow future extensions without breaking the API
class RenderSettings
{
    public RectangleI ROI { get; }
    public RenderHints Hints { get; } // Can be honored or ignored as needed
}

public IRenderHandle Render (
    ImageSurface source,
    ImageSurface destination,
    RenderSettings renderSettings)
{
    // This is the simplified approach, because it uses only the defaults
    // However, we could ignore the defaults based on our needs,
    // and specify a different set of tiles, a synchronous rendering approach, etc.
    return
        renderSettings
        .CreateDefaultRenderer() // Implementation chosen based on settings
        .StartRender(
            source,
            destination,
            tile => {
                // This lambda has a single argument
                // but there could be an overload of
                // StartRender() that accepts a lambda
                // with two arguments: the tile and the index
                // Internally, a ConcurrentQueue can allow us
                // to consume the tiles without worrying about indices
            });
}
```

I would appreciate feedback on this.

**Comment by cameronwhite** [comment]
Thanks, I think the proposed API looks generally reasonable at a first glance - I'd have to dig into the effect renderer code more myself to have stronger opinions :) 

It's mostly this that I'm questioning: 
```
// Internally, a ConcurrentQueue can allow us
// to consume the tiles without worrying about indices
```
This code should be wrapped up in some utility methods anyways, since writing a typical (tileable) effect should ideally stay just as easy as it currently is. So if that core implementation is slightly more complicated, but is more performant / reduces memory usage, then that could be a reasonable tradeoff.

Having to allocate another entire copy of all the tiles is unnecessary overhead. But if the queue makes `target_tiles` unnecessary (which I think it could?) then I wouldn't really object to the change.

**Comment by Lehonti** [comment]
Yeah, the queue could make `target_tiles` unnecessary, with the caveat that they would have to be calculated every time (although, to be fair, the effect is probably negligible).

I have removed `target_tiles` in one of the last commits.

**Comment by cameronwhite** [comment]
Thanks, I think this change to just compute `queued_tiles` every time should be fine - they're pretty cheap to compute so it's likely not much more expensive than copying from the original read-only list.

**Pull request merged**
