### PR TITLE
Update sv.po

### PR DESCRIPTION
**Pull request by eson57**
Update Swedish translation

### CODE REVIEW

**Comment by cameronwhite** [comment]
Thanks for the translation work!
It looks like the Swedish translations were also updated yesterday on https://translations.launchpad.net/pinta -  is this the same set of changes?

**Comment by eson57** [comment]
It was me also updating the launchpad version, but checking the github pot file, almost all the _new_ launchpad strings was gone again. PoEdit removed them, so no... this PR is not the same as launchpad file.
It's your decision, which is more resent.  ;)

**Comment by cameronwhite** [comment]
OK thanks! I think the launchpad translations page is still on the .pot file for the `gtk2` branch, due to the recent 1.7.1 release. I've been meaning to get that switched over to match the `master` branch, so that probably accounts for the discrepancy you noticed?

**Comment by cameronwhite** [comment]
OK, I think I've gotten things set up properly on  Launchpad now, and the master and gtk2 branch translations are both available to translate.
I'll merge this and sync it back to Launchpad - for future changes you don't need to make a PR since the Launchpad translation updates will be pulled in periodically

Thanks for your contribution!

**Pull request merged**
