### PR TITLE
Add release notes for 1.7 to appdata.

### PR DESCRIPTION
**Pull request by darkdragon-001**
Please always update release notes also in appdata file.

Taken from [here](https://github.com/flathub/com.github.PintaProject.Pinta/blob/51a00211ac74e607349459bdcba17b64b233eedf/pinta-appdata.patch).

@hfiguiere I committed your changes upstream.

### CODE REVIEW

**Comment by hfiguiere** [comment]
Cool!

FWIW I trimmed out a couple of changes from the list that I didn't feel were relevant for the flatpak.

**Comment by cameronwhite** [comment]
Thanks! I'll add this to https://github.com/PintaProject/Pinta/wiki/Release-Checklist for next time

**Comment by BeholdersEye** [comment]
Is there a way to submit an issue or a feature request to this project or are those not accepted in principle? Most github pages make it easy to do that.

**Comment by cameronwhite** [comment]
We use https://bugs.launchpad.net/pinta/+bugs as the bug database - I
would like to switch it over to Github eventually, but transitioning
is a larger undertaking

**Pull request merged**
