### PR TITLE
Modernised Icon

### PR DESCRIPTION
**Pull request by Zekiah-A**
With many of the icons within Pinta being recently updated, I believe that the Pinta icon should be as well. The current icon looks fairly outdated, especially amongst that of other apps.
image

For this reason, I am proposing an updated version of this icon, that is more modern, but stays as true to the original design as possible.

OLD:
image

NEW:
image

Extra images (for fun):
image
image

As you can see, it is practically the same in terms of the design, but I think the change of colours, shading and outlines really helps to make it look nice and new (in my opinion).

Suggestions or edits would be greatly appreciated! :+1:

### CODE REVIEW

**Comment by cameronwhite** [comment]
Thank you for working on this :)
It looks pretty good to me! I also am not a designer, so comments / opinions from others are very welcome!

I like that it has a refreshed look but is very recognizable vs the existing icon
Note that there also was an icon proposed at https://github.com/MrCarroll/pinta-snap/pulls which is quite different, but might be worth looking at if there's anything you might want to combine

**Comment by Xabian-A** [comment]
Very Nice

**Comment by jmochii** [comment]
> Thank you for working on this :) It looks pretty good to me! I also am not a designer, so comments / opinions from others are very welcome!
> 
> I like that it has a refreshed look but is very recognizable vs the existing icon Note that there also was an icon proposed at https://github.com/MrCarroll/pinta-snap/pulls which is quite different, but might be worth looking at if there's anything you might want to combine

Yes, having a look at this new icon, I definitely agree that it has a more "refreshed" look.  The revamped design is especially fitting in comparison to other apps (I use gnome, so the current one stands out just a bit!) Just wanted to mention that Zekiah has ran this idea by my several times, he has poured a ton of thought and effort into it, and from an external perspective, I would say the new design is great. It creates a cleaner aesthetic that is _carried through_ when using the app, which would make the user experience more enjoyable - and if this icon were to be picked I'd strongly believe that the app would gain popularity. Whilst my opinion is biased (I am a friend from work) I would definitely spread the word and advertise about your app, if this icon were to be picked.

The other icon is cool, however I had to think again about the dog?? I wouldn't think "Pinta" when I see a dog on an app, just being honest, no offence intended. Also, I believe it is a mere trace of an image from the Pina website. The brush clashes; it remains outdated on that logo!

So these are my views, as a potential user (I have also ran this by several colleagues at work, they seem to agree with me). I hope it's not too much of a hassle me commenting these ideas, and I hope you take them into consideration!

**Comment by igor2x** [comment]
My two cents... What I see in current and suggested icons as little bit a problem is alignment of icon. Pinta icon is "moved" little bit to far to the right. I have drawn a red line on both sites (left and right) to indicate the problem.
pic

May I suggest to move the icon little bit to the right like this:
image

**Comment by Zekiah-A** [comment]
> My two cents... What I see in current and suggested icons as little bit a problem is alignment of icon. Pinta icon is "moved" little bit to far to the right. I have drawn a red line on both sites (left and right) to indicate the problem. pic
> 
> May I suggest to move the icon little bit to the right like this: image

Good point, I see what you mean, I can try shifting it by a few pixels, and we can see what happens

**Comment by Zekiah-A** [comment]
image
Continuing the nitpick saga, it also seems that the original icon was higher than it should be, carried over into the redesign, so I will have a look into fixing this as well

**Comment by cameronwhite** [comment]
The updates look good! 👍 
Looks like there are still a couple code changes left over?
Also, there are a couple more versions of the icon for the installers: `installer/windows/Pinta.ico`, `installer/windows/logo.bmp`, and `installer/macos/pinta.icns`

**Comment by Zekiah-A** [comment]
> The updates look good! +1 Looks like there are still a couple code changes left over? Also, there are a couple more versions of the icon for the installers: `installer/windows/Pinta.ico`, `installer/windows/logo.bmp`, and `installer/macos/pinta.icns`

Yeah, my code editor decided it wanted to add spaces to the end of lines (annoying). I'll go and check for any places where the icons have not been changed, and I'll try to update all of those

**Comment by Zekiah-A** [comment]
I was able to update everything except for the macos icon, which seems to be using a ridiculous proprietary file format that I couldn't find any tools to convert for (thanks as always apple). If someone in the dev team owns an apple device to convert these, then it would be great if you could, but for now, it may just have to stay as the old logo.

**Comment by cameronwhite** [comment]
No problem, I can look into getting the .icns converted

**Comment by Zekiah-A** [comment]
:+1:  Ready for merge?

**Pull request merged**
