### PR TITLE
Update FloodTool.cs

### PR DESCRIPTION
**Pull request by nikita-yfh**
Changed default 0 tolerance to 35

### CODE REVIEW

**Comment by cameronwhite** [comment]
Are there any reasons for this particular value?
I agree it could be useful to have the value be non-zero by default, but this seemed fairly high in a couple quick tests I just did.

**Comment by NicoHood** [comment]
I dont think this is a good default.

**Comment by nikita-yfh** [comment]
If this value is taken from a file?

**Comment by cameronwhite** [comment]
In the GTK3 branch the tool settings are now saved in the preferences (#178) so I think that would address this?

**Comment by nikita-yfh** [comment]
Then this branch is useless

**Pull request closed without merging**
