### PR TITLE
Struct-valued custom enumerator for pixel offsets

### PR DESCRIPTION
**Pull request by Lehonti**
I think one shouldn't have to allocate on the heap in order to enumerate the pixel coordinates and offsets.

To be consumed by a `foreach` loop an object doesn't need to implement `IEnumerable<T>`, but only expose public methods with the corresponding names and signatures.

It is my understanding that this new approach would prevent heap allocations except when the object is explicitly used as an `IEnumerable<T>` (like in `VoronoiDiagramEffect` through an invocation of `Select`).

### CODE REVIEW

**Comment by cameronwhite** [comment]
Could you try running the effect benchmarks to see if there's a notable difference with this change? If so I'm okay with it, but otherwise the original implementation is much simpler

**Comment by cameronwhite** [comment]
Getting back to this, I ran the benchmarks myself and there is some improvement to the overall performance, so I'm okay with the change since it's a core utility used by many effects.
Could you just add some doc comments to the new classes to explain their purpose?

Before:
```
| Method      | Mean     | Error   | StdDev  | Allocated |
|------------ |---------:|--------:|--------:|----------:|
| BulgeEffect | 208.1 ms | 1.67 ms | 1.39 ms |   1.14 KB |
```

After:
```
| Method      | Mean     | Error   | StdDev  | Allocated |
|------------ |---------:|--------:|--------:|----------:|
| BulgeEffect | 196.3 ms | 2.38 ms | 2.23 ms |   1.04 KB |
```

**Comment by Lehonti** [comment]
Thank you for running the benchmarks, @cameronwhite! I tried to run them but ran into problems when NUnit refused to run the tests because they referenced an unoptimized library from Mono, and since these last few weeks have been busy I didn't have the time to figure out what the problem was.

I just added documentation comments to the new `struct`s

**Comment by cameronwhite** [comment]
No problem - I committed e2cba394917c04dacabd30a93d1fb268a05814f8 which works around those errors running the benchmarks

**Pull request merged**
