### PR TITLE
Step rotate branch

### PR DESCRIPTION
**Pull request by rajter**
Added a step rotation for the base transform tool when the left shift key is pressed.

### CODE REVIEW

**Comment by cameronwhite** [comment]
Thanks, this works well!
I think the tooltips for the transform tools should be updated to describe the new options

**Comment by rajter** [comment]
Glad you like it. I updated the tooltips as you suggested.

**Comment by cameronwhite** [comment]
Thanks! Did you intend to close this pull request?

**Comment by rajter** [comment]
No i did not. It was an accident. Sorry :D

**Pull request merged**
