### PR TITLE
Fix select tool not selcting corner canvas pixels

### PR DESCRIPTION
**Pull request by Zekiah-A**
Fixed the select tool as previously you were unable to drag select the last row of pixels on the X and Y axis

Screenshot_20220524_013912
Before: Unable to select the very edge pixels ^

Screenshot_20220524_015009
After: Now selects canvas edge pixel on x and y when mouse is dragged all the way to the edge

### CODE REVIEW

**Comment by Zekiah-A** [comment]
Also I am unsure why github displays so many commits for this PR, changes can be seen at "Files Changed"

**Comment by cameronwhite** [comment]
Good catch, thanks! I think there's also a similar issue in the mouse down handler, if you initially click below or to the right of the canvas

**Comment by Zekiah-A** [comment]
image
We may need to offset the dotted line border for the rectangle of the selection by -1px on the X and Y, as even though selection is now technically correct, because it is on the very edge of the image the dotted line there is hard to see

**Comment by cameronwhite** [comment]
Good point - I see in `DocumentSelection.Draw()` that it's being offset slightly, which is probably why the left / top is easy to see

**Comment by Zekiah-A** [comment]
image
Okay this is epic :sunglasses: everything works now

**Comment by cameronwhite** [comment]
Nice, looks good to me with that 0.5 translation removed

**Pull request merged**
