### PR TITLE
Additional operations for `BitMask`

### PR DESCRIPTION
**Pull request by Lehonti**
I'm doing this because these operations will be useful for a brush I want to make, but they could be useful on their own regardless. They include:

- Flip vertically
- Flip horizontally
- AND
- OR
- XOR
- NOT
- Clone
- Creation of submask (cloning an area)

Next, I plan to create bitmask views, but that's for another pull request

### CODE REVIEW

**Comment by cameronwhite** [comment]
- Could you please add documentation comments to the functions? I think that would be useful for the boolean operations that take a point offset, for example.

- Are all of these functions going to be used for your brush? I'd prefer to only add code that is needed, and not have to maintain code which is unused.

**Comment by Lehonti** [comment]
I plan for my brush to use OR, the flips, and the submask function; but maybe adding an OR operation without the corresponding AND and XOR would be strange.

But, admittedly, I don't plan on using the operations with an offset at the moment.

**Comment by cameronwhite** [comment]
OK, I think adding the corresponding AND and XOR seems reasonable but I'd skip the offset operations if there is not a clear use for them currently

**Comment by Lehonti** [comment]
Ok, I removed the operations with an offset. If we ever wanted to add them back we have this pull request as reference.

**Pull request merged**
