### PR TITLE
Fix dotted brushstrokes when drawing with semitransparent colors

### PR DESCRIPTION
**Pull request by khoidauminh**
### Why the issue happens:
Each line segment of the stroke in the PlainBrush is drawn independently, one after another. With semitransparent colors, the line segments overlap each other on their ends, causing the dark dots in the stroke.

### How this PR solves it:

Upon `OnMouseDown()`, we create a Cairo Path variable called `path`  as a class member, set it to null, and show the ToolLayer.

During `OnMouseMove()` events, we operate on the ToolLayer surface and clear it before drawing (we only clear for the PlainBrush), append `path` to the cairo context and after stroking, copy the new path back to the class member. Cairo will draw the entire path in one go, which gets rid of the dark dots. Performance hit is negligible.

In `OnMouseUp()` we draw the contents of the ToolLayer onto the destination Layer, clear and hide it.

The Pencil Tool isn't affected by this PR.

Paint strokes before and after applying the PR:
pinta

### CODE REVIEW

**Comment by cameronwhite** [comment]
Thanks for looking at this!
Rather than managing the surface yourself (and in particular, making a copy of it on each mouse move), I'd suggest making use of the `ToolLayer`, which is a scratch layer that's always available for tools to make use of, and is displayed right above the current layer when it's not hidden.
A good example of this is the freeform shape tool which draws to the tool layer while moving the mouse, and then just does a final draw to the actual layer on mouse up: https://github.com/PintaProject/Pinta/blob/master/Pinta.Tools/Tools/FreeformShapeTool.cs#L85

**Comment by khoidauminh** [comment]
@cameronwhite Thanks! I'll be looking into that soon

**Comment by cameronwhite** [comment]
Thanks, the ToolLayer approach looks better 👍 

Some notes from doing a bit more testing:
- Doing a single click (not a click + drag) doesn't cause anything to be drawn now
- Using a brush width of 1 seems to sometimes produce some odd results, like drawing a filled polygon from the whole sequence of mouse movements. Might be some odd interaction with the `DrawSinglePixelLine()` code path?
- If possible, it would be great to move more of the logic into the PlainBrush to avoid special casing things too much. If necessary there can be more virtual functions added to BasePaintBrush to facilitate this, e.g. requesting that the brush should use the tool layer

**Comment by khoidauminh** [comment]
Hi @cameronwhite, I just pushed a few commits that deals with the issues above:

1. Not clearing the `ToolLayer` in `OnMouseDown()` seems to have fixed the single click interaction (which, to be frank, I don't know how both the issue and the solution works).

2. For the brush width of 1, I was able to bypass checking and calling `DrawSinglePixelLine()` completely because the [code](https://github.com/PintaProject/Pinta/blob/73f5b8bcc31378f57fbc0bae4fa70688596c55ad/Pinta.Tools/Brushes/PlainBrush.cs#L68) will always force out a line, which looks like this:

ảnh
 
3. `path` seemed to be the only variable that could be brought to the inner PlainBrush class so I move it over. Currently the only code that depends on the type of `active_brush` is [this one](https://github.com/PintaProject/Pinta/blob/73f5b8bcc31378f57fbc0bae4fa70688596c55ad/Pinta.Tools/Tools/PaintBrushTool.cs#L134).

**Comment by cameronwhite** [comment]
> 1. Not clearing the `ToolLayer` in `OnMouseDown()` seems to have fixed the single click interaction (which, to be frank, I don't know how both the issue and the solution works).

I think this was because the base class OnMouseDown() calls the OnMouseMove handler to avoid dealing with single-click as a special case (https://github.com/PintaProject/Pinta/blob/35c2d7f17095613dc8590dbfab259525acccfd2e/Pinta.Tools/Tools/BaseBrushTool.cs#L75)
So a better fix would be to move the `ToolLayer.Clear()` / `ToolLayer.Hidden = false` before calling `base.OnMouseDown()` in the paintbrush tool

> 2. For the brush width of 1, I was able to bypass checking and calling `DrawSinglePixelLine()` completely because the [code](https://github.com/PintaProject/Pinta/blob/d1e8a3e29cfb316d9883d694e603e2b73ec22731/Pinta.Tools/Brushes/PlainBrush.cs#L70) will always force out a line, which looks like this:

I think the behaviour looks okay when dragging to draw a line, but doing just a single click produces some odd asymmetric antialiasing which you can see in the screenshot. The old behaviour produced a "plus" shape which I think would be more expected for that scenario


Otherwise, the changes are looking good!

**Comment by khoidauminh** [comment]
Thanks for telling me, @cameronwhite 
I'll try to tackle the remaining problems in a few days

**Comment by cameronwhite** [comment]
Looks good, thanks for contributing!

**Pull request merged**
