### PR TITLE
Creating `Angle` structure

### PR DESCRIPTION
**Pull request by Lehonti**
An idea I've got is to have this data type (especially, but not exclusively) in the effect data objects, instead of a `double`, in order to represent angles.

A potential issue is that the rounding errors that we get when converting from one unit to another could give us false negatives if we want to compare angles of different units for equality. One possibility could be making it a `class` instead of a `struct`, and use inheritance to make them unit-safe at the type level, although comparisons would require a prior conversion.

Also, if we make it into a `class` it would require heap allocations, but this might be fine still.

### CODE REVIEW

**Comment by cameronwhite** [comment]
A couple questions from a first glance:
- Is there much need to compare angle values? (the rounding issue you mentioned)
- I agree about the type safety - the user of the struct is probably still assuming that the units are in radians / degrees / etc so I'm not sure about the benefit of the struct vs just having some freestanding functions to convert between different units

Are there any examples of places in the code that would be much simpler with this utility?

**Comment by Lehonti** [comment]
@cameronwhite I don't know about much simpler, but it would make the intent clear and type-safe.

This is how types are testes in `SimpleEffectDialog`:

```csharp
			if (mType == typeof (int) && (caption == "Seed"))
				yield return CreateSeed (localizer.GetString (caption), effectData, mi, attrs);
			else if (mType == typeof (int))
				yield return CreateSlider (localizer.GetString (caption), effectData, mi, attrs);
			else if (mType == typeof (double) && (caption == "Angle" || caption == "Rotation"))
				yield return CreateAnglePicker (localizer.GetString (caption), effectData, mi, attrs);
			else if (mType == typeof (double))
				yield return CreateDoubleSlider (localizer.GetString (caption), effectData, mi, attrs);
			else if (combo && mType == typeof (string))
				yield return CreateComboBox (localizer.GetString (caption), effectData, mi, attrs);
			else if (mType == typeof (bool))
				yield return CreateCheckBox (localizer.GetString (caption), effectData, mi, attrs);
			else if (mType == typeof (PointI))
				yield return CreatePointPicker (localizer.GetString (caption), effectData, mi, attrs);
			else if (mType == typeof (PointD))
				yield return CreateOffsetPicker (localizer.GetString (caption), effectData, mi, attrs);
			else if (mType.IsEnum)
				yield return CreateEnumComboBox (localizer.GetString (caption), effectData, mi, attrs);
```

As you can see, it's not only the type that is being tested, but the caption, too, which of course limits you to that specific caption.

As for the second point, yes, the user of the class may work under certain assumptions (that the angle is expressed in a certain unit, but then it turns out it's really a different unit). One possible solution I can think of is having a type hierarchy, and making the parent `Angle` class not give any information about units, and if the user wants to access that information it would have to be done through the appropriate subclass, perhaps through an `AngleVisitor`, and then handling `RadiansAngle` and `DegreesAngle` separately.

**Comment by cameronwhite** [comment]
Thanks for the explanation!
I'd kinda lean more towards avoiding a generic Angle class and keep it simple, just having separate types for Radians and Degrees? That might require slightly more code in SimpleEffectDialog to handle the different types. But in normal usage, it's then clear what units the code is expecting to use, and there's no uncertainty about whether the code needs to be checking whether the value is using some other units

**Comment by Lehonti** [comment]
Yeah, it's a good idea, just like `HsvColor` and `RgbColor` can be converted to each other and don't share a common parent, we could have a different type for each unit of the angle.

I've now created separate `structs`, and there's no way the user will be able to overlook the unit that is being used, because the properties are named `Radians`, `Degrees`, or `Revolutions`, respectively.

**Comment by cameronwhite** [comment]
Looks good to me now 👍

**Pull request merged**
