### PR TITLE
Fix zoom in/out with Ctrl-Mousewheel

### PR DESCRIPTION
**Pull request by evgeniy-harchenko**
This feature is broken since version 2.0.

### CODE REVIEW

**Comment by cameronwhite** [comment]
Thanks for looking at this! I need to do some testing, but this might be similar to some in-progress changes on the `fix/zoom-scroll-wheel` branch for bug 1958585 (https://github.com/PintaProject/Pinta/compare/master...fix/zoom-scroll-wheel)

**Comment by JamiKettunen** [comment]
This change appears to no longer be needed, v2.1.1 (in my case installed from flathub) has working Ctrl-MouseWheel scrolling

**Comment by cameronwhite** [comment]
It's been a while since I've looked at it since I've been busy with the GTK4 port, but I think the issue (at least for bug 1958585 that I was trying to fix) was that Ctrl+wheel was able to zoom, but caused the image to shift around instead of staying centered under the point you zoomed from

**Comment by cameronwhite** [comment]
I think this change was likely correct for the GTK3 branch of Pinta - the coordinates needed to be transformed to the child canvas widget

During the GTK4 port, which had a lot of changes related to event handling, the combination of https://github.com/PintaProject/Pinta/commit/9eac98a6dd8197bcf4e8878ecb7025191921f6d5 and https://github.com/PintaProject/Pinta/commit/0d2c241678cdfb7b0e7f3f872a105b066dba3a56 now have the correct  position being used
I've included you in the contributor credits for this - thanks for looking into it!

**Pull request closed without merging**
