### PR TITLE
Add unit tests for effects and adjustments

### PR DESCRIPTION
**Pull request by cameronwhite**
This is largely ported from the tests for the old Pinta.ImageManipulation library, and compares the result of running an effect against a baseline image.

### CODE REVIEW

**Comment by Lehonti** [comment]
Thanks! I will probably be able to use this as reference if I want to add more tests

**Comment by Lehonti** [comment]
I see that this looks for exact matches. What do you think of allowing for a certain tolerances? (not saying that it has to be in this specific pull request, I mean it conceptually)

**Comment by cameronwhite** [comment]
> I see that this looks for exact matches. What do you think about allowing for certain tolerances (as in "the expected color is no more than 1% different")? (not saying that it has to be in this specific pull request, I mean it conceptually)

Conceptually that's okay but there needs to be a good reason for having the tolerance. E.g. I think the case of these effects the code is pretty mature and probably unlikely to be undergoing changes that result in minor differences?

**Comment by Lehonti** [comment]
That's a good point... the current repertoire of algorithms is deterministic and understood to work well, so the match will always be exact.

I envision Pinta having more effects in the future, though. If that happens, the idea of tolerances may be applicable.

**Pull request merged**
