### PR TITLE
Created `RandomSeed` type

### PR DESCRIPTION
**Pull request by Lehonti**
My intention is to use it in `EffectData`, just like I used `DegreesAngle` in #574

### CODE REVIEW

**Comment by cameronwhite** [comment]
Could you explain your motivations for the change please?

I don't have any real objections, but also don't see it being as useful as for angles where the different units make an explicit type more beneficial
Also, is there a reason to limit it to positive numbers and disallow INT_MAX?

**Comment by Lehonti** [comment]
The motivation would be creating the seed control based on type and not the caption. The numbers are limited to those values because `Random` doesn't produce `int`s outside of that range

**Comment by cameronwhite** [comment]
OK thanks.
Leaving the checks in is probably fine then, but could you add some documentation explaining the purpose of the class since it's not as general purpose?
This could also perhaps go in the Effects folder rather than Classes

**Comment by Lehonti** [comment]
Sure, I've moved the file and added comments

**Comment by cameronwhite** [comment]
Looks good, thanks! Agreed, the wiki docs only need to be updated after it's used for SimpleEffectDialog

**Pull request merged**
