### PR TITLE
Splitting up the huge file with multiple classes

### PR DESCRIPTION
**Pull request by arthrp**
3k lines in one file seems like a bad practice to me :)

### CODE REVIEW

**Comment by cameronwhite** [comment]
This file is actually from a third-party library (http://www.angusj.com/delphi/clipper.php), so I think it would be better to propose this change upstream - otherwise it'll be more work in the future to update Pinta to a new version of the library

**Comment by arthrp** [comment]
If it's a third party maybe it's better to include it in proper way, via Nuget - https://www.nuget.org/packages/Clipper/?

**Comment by cameronwhite** [comment]
Yes, that would be good to look into. It may complicate things for Linux distributions, though - I'm not sure how widely available this library is in most distributions' repositories, and I would expect that packagers for e.g. Debian wouldn't want to be using Nuget for dependencies

**Comment by codeprof** [comment]
Nuget can be easyly integrated in monodevelop.
See http://askubuntu.com/questions/481002/how-to-install-nuget-addin-for-monodevelop
I use this for my project TurboWavelets and it works perfectly. However don't know how to handle it if a makefile is used...

**Comment by robpvn** [comment]
I asked the Debian Mono packager about this: https://twitter.com/directhex/status/725639111495802880 

Basically they can repack the NuGet package as its own package in the distro and then depend on that package for the app, it seems. So it's doable, but adds a bit of extra effort for the packagers to maintain the app.

**Comment by arthrp** [comment]
Ok, I can try to make another pull request where I'll replace the Clipper file with nuget reference. If package maintainers and you agree, that is. 
i think benefits of having good practices in code outweigh the drawbacks, can even help maintaining with what I can. But it's for you to decide.

**Comment by cameronwhite** [comment]
ad8e8356 addresses this in the GTK3 branch, so I think this PR can be closed. Thanks!

**Pull request closed without merging**
