### PR TITLE
`Maybe` type

### PR DESCRIPTION
**Pull request by Lehonti**
Enforces null checking at type level. Value cannot be accessed if check is not made.

Intended to replace nullables where possible, for tools that may or may not be selected, and similar.

### CODE REVIEW

**Comment by cameronwhite** [comment]
This perhaps needs an example of how it would be used somewhere in the codebase. Nullable types already work pretty well IMO with the compiler warnings, so I'm not sure how significant an improvement this will be?

**Comment by Lehonti** [comment]
Good question.

I originally planned to add an example to the pull request, specifically something like `BaseTool.CurrentCursor` but it would require lots of refactoring.

The idea is to have the nullability encoded at the type level and not allow null-forgiveness and other similar hand-waving that is possible with nullable types. Once the object has been constructed it will either have (or not) a value, and the programmer will be forced to handle both cases, similar to closed type hierarchies in functional languages.

**Comment by cameronwhite** [comment]
I think `but it would require lots of refactoring` is probably my main concern here - if this is going to result in very large changes for code that isn't particularly buggy currently, or make it less readable, that may not be the best use of time versus, say, fixing some of the shape tools' bug reports. 

IMO it would be better to first do refactoring to avoid null-forgiveness uses where possible (or add checks if the code was just lazy about error handling). When we turned on nullable types, null-forgiveness was added in many places to get the code to compile and let us start catching new issues. 
The EffectData case you mentioned is a good example where I'm not sure that a Maybe type would be much of an improvement since it shouldn't really be an optional value in the first place. I haven't looked into it too much, but perhaps the base class constructor can just require the EffectData instance to be passed in?

**Comment by Lehonti** [comment]
Just to clarify, I agree that `EffectData` shouldn't be optional, I was just mentioning it as an example of nullability being a workaround to get the program to compile. I, in fact, think that a non-null instance should be passed to the base constructor

**Comment by cameronwhite** [comment]
Looking around a bit, depending on a library like https://github.com/mcintyre321/OneOf might be way to go. That would be less code to maintain ourselves and handles more general union types

**Comment by Lehonti** [comment]
Fair point. I will close this PR

**Pull request closed without merging**
